# Generated by Django 3.0 on 2019-12-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('enfants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandataire',
            fields=[
                ('mandataire_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandataire', models.CharField(choices=[('Prof', 'Professionnel'), ('P', 'Parents'), ('PE', 'Père'), ('ME', 'Mère'), ('T', 'Tuteur'), ('E', 'Enfant'), ('M', 'Medecin'), ('AP', 'Autre Professionnel'), ('A', 'Autre')], max_length=20)),
                ('autre_mandataire', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('spécialité', models.CharField(max_length=50, null=True)),
                ('téléphone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('date_demande', models.DateTimeField()),
                ('objet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_enfant', to='enfants.Enfant')),
                ('mandataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_correspondante', to='session_question.Mandataire')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('habitude', models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('V', 'Voudrais')], max_length=9, null=True)),
                ('aime', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True)),
                ('aide', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True)),
                ('content', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True)),
                ('image_correspondante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_correspondante', to='images.Image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_session', to='session_question.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_aime', models.CharField(max_length=255, null=True)),
                ('note_aide', models.CharField(max_length=255, null=True)),
                ('note_satisfaction', models.CharField(max_length=255, null=True)),
                ('professionnel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professeur', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='session_question.Question')),
            ],
        ),
    ]
