# Generated by Django 3.0 on 2019-12-04 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
        ('session_question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='enfant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enfant', to='enfants.Enfant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
