# Generated by Django 3.0 on 2019-12-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('session_question', '0002_auto_20191204_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='aide',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='aime',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='habitude',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('V', 'Voudrais')], default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='image', to='images.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='session_question.Session'),
            preserve_default=False,
        ),
    ]
