# Generated by Django 3.0 on 2019-12-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0005_auto_20191205_1704'),
        ('session_question', '0002_auto_20191205_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfant_session', to='enfants.HandicapEnfant'),
        ),
    ]
