# Generated by Django 3.0 on 2019-12-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0003_auto_20191205_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_statisfaction',
            new_name='note_satisfaction',
        ),
    ]
