# Generated by Django 3.0 on 2019-12-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionnels', '0001_initial'),
        ('session_question', '0003_auto_20191204_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='note_aide',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_aime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='note_staisfaction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='professionnel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='professionnel', to='professionnels.Professionnel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='session_question.Question'),
            preserve_default=False,
        ),
    ]
