# Generated by Django 3.0 on 2019-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0003_auto_20191205_1727'),
        ('session_question', '0004_auto_20191205_1734'),
    ]

    operations = [
    ]
