# Generated by Django 3.0 on 2019-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0005_auto_20191204_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='habitude',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non'), ('V', 'Voudrais')], max_length=9, null=True),
        ),
    ]
