# Generated by Django 3.0 on 2019-12-08 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfants', '0006_enfant_connecte'),
        ('session_question', '0005_merge_20191206_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='professionnel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_enfant', to='enfants.HandicapEnfant'),
        ),
    ]
