# Generated by Django 3.0 on 2019-12-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0005_merge_20191206_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_session', to='session_question.Session'),
        ),
    ]
