# Generated by Django 3.0 on 2019-12-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0006_auto_20191208_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='session_question.Question'),
        ),
    ]
