# Generated by Django 3.0 on 2019-12-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0007_auto_20191208_1135'),
        ('session_question', '0006_auto_20191208_1100'),
    ]

    operations = [
    ]
