# Generated by Django 3.0 on 2019-12-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0007_mandataire_note_question_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='professionnel_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_correspondante',
        ),
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='enfant',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mandataire',
        ),
        migrations.DeleteModel(
            name='Mandataire',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
