# Generated by Django 3.0 on 2019-12-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0007_auto_20191208_1041'),
        ('session_question', '0008_merge_20191208_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_enfant', to='enfants.Enfant'),
        ),
    ]
