# Generated by Django 3.0 on 2019-12-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0009_auto_20191209_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandataire',
            fields=[
                ('mandataire_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandataire', models.CharField(choices=[('Prof', 'Professionnel'), ('P', 'Parents'), ('T', 'Tuteur'), ('E', 'Enfant'), ('M', 'Medecin'), ('AP', 'Autre Professionnel'), ('A', 'Autre')], max_length=20, null=True)),
                ('autre_mandataire', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('spécialité', models.CharField(max_length=50, null=True)),
                ('téléphone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('date_demande', models.DateTimeField()),
                ('objet', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='mandataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_correspondante', to='session_question.Mandataire'),
        ),
    ]
