# Generated by Django 3.0 on 2019-12-10 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0010_auto_20191210_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 22, 59, 28, 944389)),
        ),
    ]
