# Generated by Django 3.0 on 2019-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0011_auto_20191210_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
