# Generated by Django 3.0 on 2019-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0012_auto_20191210_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandataire',
            name='date_demande',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mandataire',
            name='mandataire',
            field=models.CharField(choices=[('Prof', 'Professionnel'), ('P', 'Parents'), ('PE', 'Père'), ('ME', 'Mère'), ('T', 'Tuteur'), ('E', 'Enfant'), ('M', 'Medecin'), ('AP', 'Autre Professionnel'), ('A', 'Autre')], max_length=20, null=True),
        ),
    ]
