# Generated by Django 3.0 on 2019-12-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0013_auto_20191211_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandataire',
            name='autre_mandataire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mandataire',
            name='mandataire',
            field=models.CharField(choices=[('Prof', 'Professionnel'), ('P', 'Parents'), ('PE', 'Père'), ('ME', 'Mère'), ('T', 'Tuteur'), ('E', 'Enfant'), ('M', 'Medecin'), ('AP', 'Autre Professionnel'), ('A', 'Autre')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
