# Generated by Django 3.0 on 2019-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0014_auto_20191211_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandataire',
            name='date_demande',
            field=models.DateTimeField(),
        ),
    ]
