# Generated by Django 3.0 on 2019-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20191206_1124'),
        ('images', '0002_auto_20191205_1727'),
    ]

    operations = [
    ]
