# Generated by Django 3.0 on 2019-12-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_merge_20191206_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
    ]
