# Generated by Django 2.2.7 on 2019-12-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfants',
            name='age',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enfants',
            name='handicap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicap', to='enfants.Handicaps'),
        ),
    ]
