# Generated by Django 2.2.7 on 2019-12-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handicaps',
            fields=[
                ('handicap_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_handicap', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Enfants',
            fields=[
                ('enfant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('handicap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicaps', to='enfants.Handicaps')),
            ],
        ),
    ]
