# Generated by Django 3.0 on 2019-12-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('enfant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('handicap_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_handicap', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HandicapEnfant',
            fields=[
                ('handicap_enfant_id', models.AutoField(primary_key=True, serialize=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfant_h', to='enfants.Enfant')),
                ('handicap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handicap_h', to='enfants.Handicap')),
            ],
        ),
    ]
