# Generated by Django 3.0 on 2019-12-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='handicap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handicaps', to='enfants.Handicap'),
        ),
        migrations.CreateModel(
            name='HandicapEnfant',
            fields=[
                ('handicap_enfant_id', models.AutoField(primary_key=True, serialize=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfants.Enfant')),
                ('handicap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfants.Handicap')),
            ],
        ),
    ]
