# Generated by Django 2.2.7 on 2019-12-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfants',
            name='handicap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handicaps', to='enfants.Handicaps'),
        ),
        migrations.CreateModel(
            name='HandicapEnfant',
            fields=[
                ('handicap_enfant_id', models.AutoField(primary_key=True, serialize=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfants.Enfants')),
                ('handicap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfants.Handicaps')),
            ],
        ),
    ]
