# Generated by Django 3.0 on 2019-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
