# Generated by Django 3.0 on 2019-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0002_auto_20191212_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnecontact',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
