# Generated by Django 3.0 on 2019-12-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0002_auto_20191204_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='handicap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handicap', to='enfants.Handicap'),
        ),
    ]
