# Generated by Django 2.2.7 on 2019-12-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0002_auto_20191205_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enfants',
            new_name='Enfant',
        ),
        migrations.RenameModel(
            old_name='Handicaps',
            new_name='Handicap',
        ),
    ]
