# Generated by Django 3.0 on 2019-12-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0002_auto_20191211_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='date_naissance',
        ),
    ]
