# Generated by Django 3.0 on 2019-12-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_question', '0006_auto_20191204_2302'),
        ('enfants', '0002_auto_20191204_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enfant',
            new_name='Enfants',
        ),
    ]
