# Generated by Django 2.2.7 on 2019-12-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0003_auto_20191205_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='handicap',
        ),
    ]
