# Generated by Django 3.0 on 2019-12-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0003_auto_20191204_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Handicap',
            new_name='Handicaps',
        ),
    ]
