# Generated by Django 3.0 on 2019-12-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0004_remove_enfant_handicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapenfant',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfant_h', to='enfants.Enfant'),
        ),
        migrations.AlterField(
            model_name='handicapenfant',
            name='handicap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handicap_h', to='enfants.Handicap'),
        ),
    ]
