# Generated by Django 3.0 on 2019-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0007_auto_20191208_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneContact',
            fields=[
                ('personne_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contact', models.CharField(max_length=50)),
                ('prenom_contact', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('P', 'Père'), ('M', 'Mère'), ('T', 'Tuteur'), ('F', 'Frère'), ('S', 'Soeur'), ('A', 'Autre')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='enfant',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
