# Generated by Django 3.0 on 2019-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0008_auto_20191212_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnecontact',
            name='enfant',
        ),
        migrations.DeleteModel(
            name='InfoSupplementaire',
        ),
        migrations.DeleteModel(
            name='PersonneContact',
        ),
    ]
