# Generated by Django 3.0 on 2019-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0010_auto_20191211_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosupplementaire',
            name='id',
        ),
        migrations.AddField(
            model_name='infosupplementaire',
            name='info_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
