# Generated by Django 3.0 on 2019-12-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0010_infosupplementaire_personnecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapenfant',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfant_h', to='enfants.Enfant'),
        ),
        migrations.AlterField(
            model_name='handicapenfant',
            name='handicap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handicap_h', to='enfants.Handicap'),
        ),
        migrations.AlterField(
            model_name='infosupplementaire',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_enfant', serialize=False, to='enfants.Enfant'),
        ),
        migrations.AlterField(
            model_name='personnecontact',
            name='enfant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfant', to='enfants.Enfant'),
        ),
    ]
