# Generated by Django 3.0 on 2019-12-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0011_auto_20191212_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosupplementaire',
            name='enfant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_enfant', serialize=False, to='enfants.Enfant'),
        ),
    ]
