# Generated by Django 3.0 on 2019-12-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0011_auto_20191211_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infosupplementaire',
            old_name='info_id',
            new_name='info_supp_id',
        ),
    ]
