# Generated by Django 2.2.7 on 2019-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('professionnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=42)),
                ('nom', models.CharField(max_length=42)),
                ('prenom', models.CharField(max_length=42)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
