# Generated by Django 3.0 on 2019-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('professionnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=42)),
                ('prenom', models.CharField(max_length=42)),
                ('profession', models.CharField(choices=[('Erg', 'Ergothérapeute'), ('Psy', 'Psychologue'), ('Ed', 'Educateur'), ('Ki', 'Kinésithérapeute'), ('En', 'Enseignant'), ('Au', 'Autre')], max_length=42, null=True)),
                ('autre_profession', models.CharField(max_length=42, null=True)),
                ('telephone', models.CharField(max_length=12)),
                ('user', models.IntegerField(null=True)),
            ],
        ),
    ]
