# Generated by Django 3.0 on 2019-12-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionnels', '0003_professionnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionnel',
            name='email',
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
