# Generated by Django 3.0 on 2019-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionnels', '0004_auto_20191210_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
